// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "is2_types.h"
#include <RcppEigen.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// rng32
uint32_t rng32();
RcppExport SEXP is2_rng32() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rng32());
    return __result;
END_RCPP
}
// getSeed
int getSeed();
RcppExport SEXP is2_getSeed() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(getSeed());
    return __result;
END_RCPP
}
// RQMC
Rcpp::NumericVector RQMC(int qmc, int N, int dx, int ns, Rcpp::NumericVector x);
RcppExport SEXP is2_RQMC(SEXP qmcSEXP, SEXP NSEXP, SEXP dxSEXP, SEXP nsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type qmc(qmcSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(RQMC(qmc, N, dx, ns, x));
    return __result;
END_RCPP
}
// QMC
Rcpp::NumericVector QMC(int qmc, int N, int dx, Rcpp::NumericVector x);
RcppExport SEXP is2_QMC(SEXP qmcSEXP, SEXP NSEXP, SEXP dxSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type qmc(qmcSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(QMC(qmc, N, dx, x));
    return __result;
END_RCPP
}
