# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rng32 <- function() {
    .Call('is2_rng32', PACKAGE = 'RcppSQMC')
}

getSeed <- function() {
    .Call('is2_getSeed', PACKAGE = 'RcppSQMC')
}

RQMC <- function(qmc, N, dx, ns, x) {
    .Call('is2_RQMC', PACKAGE = 'RcppSQMC', qmc, N, dx, ns, x)
}

QMC <- function(qmc, N, dx, x) {
    .Call('is2_QMC', PACKAGE = 'RcppSQMC', qmc, N, dx, x)
}

